export const players = [
	{
		playerName: "Bieda Wincenty",
		goals: 0,
		assists: 0,
		yellowCards: 0,
		redCards: 0,
		minutes: 24,
	},
	{
		playerName: "Baranowski Piotr",
		goals: 1,
		assists: 0,
		yellowCards: 2,
		redCards: 0,
		minutes: 333,
	},
	{
		playerName: "Ciszek Jarosław",
		goals: 3,
		assists: 2,
		yellowCards: 0,
		redCards: 0,
		minutes: 808,
	},
	{
		playerName: "Furtak Jan",
		goals: 6,
		assists: 7,
		yellowCards: 0,
		redCards: 0,
		minutes: 965,
	},
	{
		playerName: "Hadała Kamil",
		goals: 0,
		assists: 0,
		yellowCards: 2,
		redCards: 0,
		minutes: 935,
	},
	{
		playerName: "Kluska Emil",
		goals: 1,
		assists: 4,
		yellowCards: 2,
		redCards: 0,
		minutes: 355,
	},
	{
		playerName: "Kociołek Jakub",
		goals: 0,
		assists: 0,
		yellowCards: 0,
		redCards: 0,
		minutes: 8,
	},
	{
		playerName: "Kluska Kamil",
		goals: 6,
		assists: 1,
		yellowCards: 7,
		redCards: 0,
		minutes: 1057,
	},
	{
		playerName: "Ksepko Michał",
		goals: 0,
		assists: 0,
		yellowCards: 0,
		redCards: 0,
		minutes: 46,
	},
	{
		playerName: "Leja Mariusz",
		goals: 0,
		assists: 0,
		yellowCards: 0,
		redCards: 0,
		minutes: 45,
	},
	{
		playerName: "Lewicki Radosław",
		goals: 0,
		assists: 0,
		yellowCards: 0,
		redCards: 0,
		minutes: 450,
	},
	{
		playerName: "Leśniak Adrian",
		goals: 0,
		assists: 0,
		yellowCards: 0,
		redCards: 0,
		minutes: 45,
	},
	{
		playerName: "Leśniak Krystian",
		goals: 5,
		assists: 4,
		yellowCards: 1,
		redCards: 0,
		minutes: 430,
	},
	{
		playerName: "Łukasik Kornel",
		goals: 1,
		assists: 0,
		yellowCards: 2,
		redCards: 0,
		minutes: 371,
	},
	{
		playerName: "Migacz Tomasz",
		goals: 0,
		assists: 0,
		yellowCards: 1,
		redCards: 0,
		minutes: 1156,
	},
	{
		playerName: "Morawski Miłosz",
		goals: 1,
		assists: 1,
		yellowCards: 2,
		redCards: 0,
		minutes: 982,
	},
	{
		playerName: "Respondek Kamil",
		goals: 3,
		assists: 6,
		yellowCards: 1,
		redCards: 0,
		minutes: 900,
	},
	{
		playerName: "Respondek Ksawier",
		goals: 0,
		assists: 0,
		yellowCards: 0,
		redCards: 0,
		minutes: 60,
	},
	{
		playerName: "Siwiński Paweł",
		goals: 0,
		assists: 0,
		yellowCards: 2,
		redCards: 0,
		minutes: 1075,
	},
	{
		playerName: "Skrzypiec Marcin",
		goals: 0,
		assists: 0,
		yellowCards: 1,
		redCards: 0,
		minutes: 237,
	},
	{
		playerName: "Sobczak Karol",
		goals: 2,
		assists: 0,
		yellowCards: 1,
		redCards: 0,
		minutes: 555,
	},
	{
		playerName: "Tarasek Bartłomiej",
		goals: 0,
		assists: 0,
		yellowCards: 1,
		redCards: 0,
		minutes: 25,
	},

	{
		playerName: "Wodziak Bartosz",
		goals: 0,
		assists: 0,
		yellowCards: 4,
		redCards: 0,
		minutes: 841,
	},
	{
		playerName: "Wowk Grzegorz",
		goals: 3,
		assists: 1,
		yellowCards: 0,
		redCards: 0,
		minutes: 960,
	},
	{
		playerName: "Zapała Kacper",
		goals: 0,
		assists: 0,
		yellowCards: 0,
		redCards: 0,
		minutes: 10,
	},
];
