export const players = [
	{
		playerName: "Bieda Wincenty",
		goals: 0,
		assists: 0,
		yellowCards: 0,
		redCards: 0,
		minutes: 24,
	},
	{
		playerName: "Bołoz Jacek",
		goals: 0,
		assists: 0,
		yellowCards: 0,
		redCards: 0,
		minutes: 433,
	},
	{
		playerName: "Baranowski Piotr",
		goals: 2,
		assists: 1,
		yellowCards: 2,
		redCards: 0,
		minutes: 527,
	},
	{
		playerName: "Ciszek Jarosław",
		goals: 3,
		assists: 3,
		yellowCards: 0,
		redCards: 0,
		minutes: 1163,
	},
	{
		playerName: "Furtak Jan",
		goals: 17,
		assists: 10,
		yellowCards: 1,
		redCards: 0,
		minutes: 1625,
	},
	{
		playerName: "Hadała Kamil",
		goals: 0,
		assists: 0,
		yellowCards: 5,
		redCards: 0,
		minutes: 1475,
	},
	{
		playerName: "Kluska Emil",
		goals: 1,
		assists: 4,
		yellowCards: 2,
		redCards: 0,
		minutes: 355,
	},
	{
		playerName: "Kociołek Jakub",
		goals: 0,
		assists: 0,
		yellowCards: 0,
		redCards: 0,
		minutes: 18,
	},
	{
		playerName: "Kluska Kamil",
		goals: 11,
		assists: 3,
		yellowCards: 11,
		redCards: 0,
		minutes: 1675,
	},
	{
		playerName: "Ksepko Michał",
		goals: 0,
		assists: 0,
		yellowCards: 0,
		redCards: 0,
		minutes: 46,
	},
	{
		playerName: "Leja Mariusz",
		goals: 0,
		assists: 0,
		yellowCards: 1,
		redCards: 0,
		minutes: 110,
	},
	{
		playerName: "Lewicki Radosław",
		goals: 0,
		assists: 1,
		yellowCards: 1,
		redCards: 0,
		minutes: 540,
	},
	{
		playerName: "Leśniak Adrian",
		goals: 0,
		assists: 0,
		yellowCards: 2,
		redCards: 0,
		minutes: 275,
	},
	{
		playerName: "Leśniak Krystian",
		goals: 6,
		assists: 4,
		yellowCards: 1,
		redCards: 0,
		minutes: 520,
	},
	{
		playerName: "Łukasik Kornel",
		goals: 1,
		assists: 0,
		yellowCards: 3,
		redCards: 0,
		minutes: 550,
	},
	{
		playerName: "Migacz Tomasz",
		goals: 0,
		assists: 0,
		yellowCards: 1,
		redCards: 0,
		minutes: 1876,
	},
	{
		playerName: "Morawski Miłosz",
		goals: 2,
		assists: 2,
		yellowCards: 4,
		redCards: 0,
		minutes: 1553,
	},
	{
		playerName: "Respondek Kamil",
		goals: 5,
		assists: 8,
		yellowCards: 1,
		redCards: 0,
		minutes: 1610,
	},
	{
		playerName: "Respondek Ksawier",
		goals: 0,
		assists: 0,
		yellowCards: 0,
		redCards: 0,
		minutes: 95,
	},
	{
		playerName: "Siwiński Paweł",
		goals: 0,
		assists: 0,
		yellowCards: 4,
		redCards: 1,
		minutes: 1615,
	},
	{
		playerName: "Sobczak Karol",
		goals: 6,
		assists: 1,
		yellowCards: 1,
		redCards: 0,
		minutes: 1153,
	},
	{
		playerName: "Tarasek Bartłomiej",
		goals: 0,
		assists: 0,
		yellowCards: 1,
		redCards: 0,
		minutes: 25,
	},
	{
		playerName: "Tokarski Andrzej",
		goals: 0,
		assists: 1,
		yellowCards: 1,
		redCards: 0,
		minutes: 525,
	},

	{
		playerName: "Wodziak Bartosz",
		goals: 0,
		assists: 0,
		yellowCards: 4,
		redCards: 0,
		minutes: 841,
	},
	{
		playerName: "Wowk Grzegorz",
		goals: 3,
		assists: 2,
		yellowCards: 0,
		redCards: 0,
		minutes: 1410,
	},
	{
		playerName: "Zapała Kacper",
		goals: 0,
		assists: 0,
		yellowCards: 0,
		redCards: 0,
		minutes: 17,
	},
];
