export const players = [
	{
		playerName: "Bieda Wincenty",
		goals: 0,
		assists: 0,
		yellowCards: 0,
		redCards: 0,
		minutes: 24,
	},
	{
		playerName: "Baranowski Piotr",
		goals: 1,
		assists: 0,
		yellowCards: 2,
		redCards: 0,
		minutes: 253,
	},
	{
		playerName: "Ciszek Jarosław",
		goals: 3,
		assists: 1,
		yellowCards: 0,
		redCards: 0,
		minutes: 654,
	},
	{
		playerName: "Furtak Jan",
		goals: 6,
		assists: 7,
		yellowCards: 0,
		redCards: 0,
		minutes: 830,
	},
	{
		playerName: "Hadała Kamil",
		goals: 0,
		assists: 0,
		yellowCards: 2,
		redCards: 0,
		minutes: 665,
	},
	{
		playerName: "Kluska Emil",
		goals: 1,
		assists: 4,
		yellowCards: 2,
		redCards: 0,
		minutes: 355,
	},
	{
		playerName: "Kociołek Jakub",
		goals: 0,
		assists: 0,
		yellowCards: 0,
		redCards: 0,
		minutes: 8,
	},
	{
		playerName: "Kluska Kamil",
		goals: 6,
		assists: 1,
		yellowCards: 6,
		redCards: 0,
		minutes: 787,
	},
	{
		playerName: "Ksepko Michał",
		goals: 0,
		assists: 0,
		yellowCards: 0,
		redCards: 0,
		minutes: 46,
	},
	{
		playerName: "Leja Mariusz",
		goals: 0,
		assists: 0,
		yellowCards: 0,
		redCards: 0,
		minutes: 30,
	},
	{
		playerName: "Lewicki Radosław",
		goals: 0,
		assists: 0,
		yellowCards: 0,
		redCards: 0,
		minutes: 275,
	},
	{
		playerName: "Leśniak Adrian",
		goals: 0,
		assists: 0,
		yellowCards: 0,
		redCards: 0,
		minutes: 0,
	},
	{
		playerName: "Leśniak Krystian",
		goals: 5,
		assists: 4,
		yellowCards: 1,
		redCards: 0,
		minutes: 430,
	},
	{
		playerName: "Łukasik Kornel",
		goals: 1,
		assists: 0,
		yellowCards: 2,
		redCards: 0,
		minutes: 338,
	},
	{
		playerName: "Migacz Tomasz",
		goals: 0,
		assists: 0,
		yellowCards: 0,
		redCards: 0,
		minutes: 886,
	},
	{
		playerName: "Morawski Miłosz",
		goals: 1,
		assists: 0,
		yellowCards: 2,
		redCards: 0,
		minutes: 712,
	},
	{
		playerName: "Respondek Kamil",
		goals: 3,
		assists: 5,
		yellowCards: 1,
		redCards: 0,
		minutes: 630,
	},
	{
		playerName: "Respondek Ksawier",
		goals: 0,
		assists: 0,
		yellowCards: 0,
		redCards: 0,
		minutes: 35,
	},
	{
		playerName: "Siwiński Paweł",
		goals: 0,
		assists: 0,
		yellowCards: 2,
		redCards: 0,
		minutes: 805,
	},
	{
		playerName: "Skrzypiec Marcin",
		goals: 0,
		assists: 0,
		yellowCards: 1,
		redCards: 0,
		minutes: 144,
	},
	{
		playerName: "Sobczak Karol",
		goals: 0,
		assists: 0,
		yellowCards: 0,
		redCards: 0,
		minutes: 475,
	},
	{
		playerName: "Tarasek Bartłomiej",
		goals: 0,
		assists: 0,
		yellowCards: 1,
		redCards: 0,
		minutes: 25,
	},

	{
		playerName: "Wodziak Bartosz",
		goals: 0,
		assists: 0,
		yellowCards: 2,
		redCards: 0,
		minutes: 630,
	},
	{
		playerName: "Wowk Grzegorz",
		goals: 1,
		assists: 1,
		yellowCards: 0,
		redCards: 0,
		minutes: 690,
	},
	{
		playerName: "Zapała Kacper",
		goals: 0,
		assists: 0,
		yellowCards: 0,
		redCards: 0,
		minutes: 10,
	},
];
